# Generated by Django 2.2.17 on 2021-02-21 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50, verbose_name='Nome')),
                ('senha', models.CharField(max_length=15, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('divida', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo devedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dívidas', to='new_credit.Usuario')),
            ],
            options={
                'verbose_name': 'Dívida',
                'verbose_name_plural': 'Dividas',
            },
        ),
    ]
